# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-22 18:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_no', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('complaint_sub', models.CharField(max_length=150)),
                ('complaint_details', models.CharField(max_length=300)),
                ('complaint_status', models.CharField(default='open', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='flat_info',
            fields=[
                ('flat_no', models.IntegerField(primary_key=True, serialize=False)),
                ('contact_no', models.IntegerField()),
                ('owner_name', models.CharField(max_length=50)),
                ('residence', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('members', models.IntegerField()),
                ('floor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='fyi1',
            fields=[
                ('financial_year', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('maintenance_counter', models.FloatField(blank=True, default=0.0, null=True)),
                ('parking_counter', models.FloatField(blank=True, default=0.0, null=True)),
                ('sinkingfund_counter', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_no', models.CharField(blank=True, max_length=4, null=True)),
                ('date_time', models.DateTimeField(auto_now=True, null=True)),
                ('maintenance_counter', models.FloatField(blank=True, default=0.0, null=True)),
                ('parking_counter', models.FloatField(blank=True, default=0.0, null=True)),
                ('sinkingfund_counter', models.FloatField(blank=True, default=0.0, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('fine', models.FloatField(blank=True, default=0.0, null=True)),
                ('total_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.fyi1')),
            ],
        ),
        migrations.CreateModel(
            name='maintenance_type',
            fields=[
                ('maintenance_header', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('counter', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.IntegerField(default='', null=True)),
                ('address', models.CharField(default='', max_length=50, null=True)),
                ('designation', models.CharField(default='', max_length=50, null=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_sub', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('notice_details', models.CharField(max_length=300)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.management')),
            ],
        ),
        migrations.CreateModel(
            name='tid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_no', models.IntegerField(blank=True, null=True)),
                ('maintenance_count', models.FloatField(blank=True, default=0.0, null=True)),
                ('parking_count', models.FloatField(blank=True, default=0.0, null=True)),
                ('sinkingfund_count', models.FloatField(blank=True, default=0.0, null=True)),
                ('last_id', models.IntegerField(blank=True, default=0, null=True)),
                ('sinkingfund_paid', models.FloatField(blank=True, default=0.0, null=True)),
                ('sinkingfund_fine_paid', models.FloatField(blank=True, default=0.0, null=True)),
                ('parking_paid', models.FloatField(blank=True, default=0.0, null=True)),
                ('parking_fine_paid', models.FloatField(blank=True, default=0.0, null=True)),
                ('maintenance_paid', models.FloatField(blank=True, default=0.0, null=True)),
                ('maintenance_fine_paid', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='maintenance',
            name='type_of_maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.maintenance_type'),
        ),
    ]
