# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-22 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='management',
            old_name='username',
            new_name='user',
        ),
    ]
