# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-27 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20180123_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='query',
            field=models.CharField(default=2, max_length=300),
            preserve_default=False,
        ),
    ]
