# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-27 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_contact_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='query',
            field=models.TextField(max_length=300),
        ),
    ]
