# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-27 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20180127_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_sub', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('event_details', models.CharField(max_length=300)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.management')),
            ],
        ),
    ]
