# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-27 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='email',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
